### ISSUE TITLE
Loading page

### ISSUE THREAD

**Issue by ClairePUK** [cast-fuse/parkinsons-and-me#140]
Could the quote box, font and colour be the same style as the previous pages - the "Parkinson's UK voice"? Still aligned in the middle of the page though.

**Comment by andrewMacmurray** [comment]
@ClairePUK the tilted quote box doesn't really work in this place (as it was only meant for the top of the page) and it was extremely fiddly to implement in the first place. I'd suggest keeping it as it is for now and later on if you have more work done change it then

**Comment by ClairePUK** [comment]
Sure, could we change the colour to the blue?

**Comment by andrewMacmurray** [comment]
yep, can do that

**Comment by andrewMacmurray** [comment]
closed with pr #136
