### ISSUE TITLE
Results page

### ISSUE THREAD

**Issue by ClairePUK** [cast-fuse/parkinsons-and-me#141]
- Could the top quote box be the same style and font as the previous pages - the "Parkinson's UK voice". (This says: Here's your personalised list of Parkinson's service) The other quote box style, colour, fonts are fine. 

- Could we close up the line space between 'Come back and visit your page any time:' and the URL?

- Can we make sure all the copy is the same as the Google doc? https://docs.google.com/document/d/11Augc7C7knIRDUHNbSL0HZPdRThxiAJbpbmqkUv5Lvw/edit?usp=sharing

**Comment by ivanmauricio** [comment]
@ClairePUK 

> Could the top quote box be the same style and font as the previous pages - the "Parkinson's UK voice". (This says: Here's your personalised list of Parkinson's service) The other quote box style, colour, fonts are fine.

This bit of text is too long to fit in the tilted quote box. It will mean it would overspill on different devices. This is why we changed the text on the age page to 'Can we ask your age?' If you can think of a more succinct title then we can change it, otherwise I'd suggest leaving it as it is.

> Could we close up the line space between 'Come back and visit your page any time:' and the URL?

We'll get onto this.

> Can we make sure all the copy is the same as the Google doc? 

As far as I can see the copy is fine. Is there anything specific that isn't right?

**Comment by ClairePUK** [comment]
Could we try: Here's your recommended Parkinson's services

**Comment by ivanmauricio** [comment]
![screen shot 2017-05-10 at 15 50 31](https://cloud.githubusercontent.com/assets/12462448/25904878/708c593e-3598-11e7-886d-154316c9c6c3.png)

Still a bit long...

**Comment by ivanmauricio** [comment]
![screen shot 2017-05-10 at 15 52 18](https://cloud.githubusercontent.com/assets/12462448/25904967/acf29528-3598-11e7-9d07-413194e1e51f.png)

**Comment by ivanmauricio** [comment]
Can I suggest leaving the original quote box but changing the font to the 'Parkinson's voice' one.

**Comment by ClairePUK** [comment]
Can I try two more? Then I'll admit defeat:

1. Here's your recommendations
2. Your recommended Parkinson's services

Thank you

**Comment by andrewMacmurray** [comment]
This one fits
![screen shot 2017-05-11 at 14 33 33](https://cloud.githubusercontent.com/assets/14013616/25951851/d9b0cddc-3656-11e7-9736-bf17b9b6f041.png)

**Comment by ClairePUK** [comment]
Yes, perfect - that'll do! (with a lower case 'r' 👍 )

**Comment by andrewMacmurray** [comment]
closed with pr #144
