### ISSUE TITLE
Error message from URL 

### ISSUE THREAD

**Issue by ClairePUK** [cast-fuse/parkinsons-and-me#146]
![image](https://cloud.githubusercontent.com/assets/26407154/26057025/9edfa2fc-396f-11e7-8e66-e166be13c58c.png)

@ivanmauricio @andrewMacmurray 

I'm getting this error message when I click on the URL or try to copy and paste the URL into another browser. It's happening every time.

**Comment by andrewMacmurray** [comment]
I checked and that was a url that you made on staging not production so it won't be visible there

**Comment by andrewMacmurray** [comment]
https://parkinsons-and-me-staging.herokuapp.com/#my-results/fc1174b9

**Comment by ClairePUK** [comment]
Okay, will make sure I test on production.
