### ISSUE TITLE
Small email positioning change

### ISSUE THREAD

**Issue by ClairePUK** [cast-fuse/parkinsons-and-me#148]
Email copy/layouts is fine, bar two things:

![image](https://cloud.githubusercontent.com/assets/26407154/26057254/c9269632-3970-11e7-9620-a9c892c5784d.png)

Could the CTA buttons be aligned centre?

![image](https://cloud.githubusercontent.com/assets/26407154/26057284/e9fbe178-3970-11e7-92b9-e25a1a67f2f5.png)

Could this be single line spacing?

Then this is all signed off, just waiting on verifying the domain.

**Comment by andrewMacmurray** [comment]
@ClairePUK I don't think this is priority 2 ;)

**Comment by ClairePUK** [comment]
If it's stopping it being signed off it's a priority 2 in my eyes!

**Comment by andrewMacmurray** [comment]
@ClairePUK why is this stopping it getting signed off?! it's an MVP at this stage

**Comment by ClairePUK** [comment]
If you're able to make the changes, and it's not too time-consuming, that would be great.

**Comment by ivanmauricio** [comment]
closed via #149
