### ISSUE TITLE
Postcode in Parkinson's Nurse Url

### ISSUE THREAD

**Issue by andrewMacmurray** [cast-fuse/parkinsons-and-me#47]
would be good to get the postcode into the url to the Parkinson's Nurse Url

**Comment by ClairePUK** [comment]
https://www.parkinsons.org.uk/local-support?distance%5Bpostal_code%5D=sw18+3bn&distance%5Bsearch_distance%5D=100&distance%5Bsearch_units%5D=mile

**Comment by andrewMacmurray** [comment]
closed with pr #135
