### ISSUE TITLE
Survey at the end

### ISSUE THREAD

**Issue by andrewMacmurray** [cast-fuse/parkinsons-and-me#48]
Need to either embed a survey at the end of the process or link to a survey

**Comment by ivanmauricio** [comment]
Prototype testing questionnaire: https://docs.google.com/forms/d/1rrPNT0GtthACdNwFUTbW_QSIb37MXd94SpPcNurK7Rs/edit

**Comment by andrewMacmurray** [comment]
new survey url https://goo.gl/forms/Ld8X0fSkdMF5wvlo2

**Comment by andrewMacmurray** [comment]
closed with #135
